// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC8Fp7UZQk23R1Lyq_uh0oXveetimmWPE',
    appId: '1:323217613230:web:d69550123af382f735283f',
    messagingSenderId: '323217613230',
    projectId: 'flutter-push-e7e80',
    authDomain: 'flutter-push-e7e80.firebaseapp.com',
    storageBucket: 'flutter-push-e7e80.appspot.com',
    measurementId: 'G-GDM9H3JZG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcK_uAmurS2LMh5sYusdGCtcrYZFl5xRA',
    appId: '1:323217613230:android:6a77cd8b95e7fcb935283f',
    messagingSenderId: '323217613230',
    projectId: 'flutter-push-e7e80',
    storageBucket: 'flutter-push-e7e80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVva2i8_rX6jikpVA3nnKF9wujfU62fdg',
    appId: '1:323217613230:ios:ec86182bb22cf97035283f',
    messagingSenderId: '323217613230',
    projectId: 'flutter-push-e7e80',
    storageBucket: 'flutter-push-e7e80.appspot.com',
    androidClientId:
        '323217613230-mee0k3drvd768fp740ou2imjbpb1drki.apps.googleusercontent.com',
    iosClientId:
        '323217613230-5l5abuqf7uc5072blgg4f5ovf2k4h2k3.apps.googleusercontent.com',
    iosBundleId: 'com.jeancarsanchez.pushapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVva2i8_rX6jikpVA3nnKF9wujfU62fdg',
    appId: '1:323217613230:ios:ec86182bb22cf97035283f',
    messagingSenderId: '323217613230',
    projectId: 'flutter-push-e7e80',
    storageBucket: 'flutter-push-e7e80.appspot.com',
    androidClientId:
        '323217613230-mee0k3drvd768fp740ou2imjbpb1drki.apps.googleusercontent.com',
    iosClientId:
        '323217613230-5l5abuqf7uc5072blgg4f5ovf2k4h2k3.apps.googleusercontent.com',
    iosBundleId: 'com.jeancarsanchez.pushapp',
  );
}
